### ISSUE TITLE
installation difficulties on windows

### ISSUE THREAD

**Issue by heartlocket** [maua-maua-maua/maua#4]
When I try to do the basic install I run into a repeated error:

 Running command git submodule update --init --recursive -q
  error: unable to create file docs/d0/d14/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compatie5920c849e839ebb9f8c57349c900796.html: Filename too long

_attn/cutlass'
  error: subprocess-exited-with-error

  × git submodule update --init --recursive -q did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by JCBrouwer** [comment]
Hmmm interesting. I'm having trouble reproducing the issue. On my system (Ubuntu 20.04) with a clean python 3.8, 3.9, or 3.10 environment the install works.

I've googled the file and it seems to be [part of CUDNN](https://github.com/NVIDIA/cudnn-frontend/blob/main/docs/d0/d14/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compatie5920c849e839ebb9f8c57349c900796.html).

Could you try running `pip install nvidia-cudnn-cu116` to check if this is what's causing the error?

Also could you give some more details on the system that you're trying to install on (operating system, python version, CUDA version)?

**Comment by heartlocket** [comment]
Yes, will get back to you with OS info and the results of that test this afternoon

**Comment by heartlocket** [comment]
>  Hmmm interesting. I'm having trouble reproducing the issue. On my system (Ubuntu 20.04) with a clean python 3.8, 3.9, or 3.10 environment the install works.
> 
> I've googled the file and it seems to be [part of CUDNN](https://github.com/NVIDIA/cudnn-frontend/blob/main/docs/d0/d14/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compatie5920c849e839ebb9f8c57349c900796.html).
> 
> Could you try running `pip install nvidia-cudnn-cu116` to check if this is what's causing the error?
> 
> Also could you give some more details on the system that you're trying to install on (operating system, python version, CUDA version)?

Sorry, for the delay. I am using windows 11, python 3.10.7, CUDA 11.7

When I try to run that command it throws the following error:
```
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\heart\AppData\Local\Temp\pip-install-qbqjk33c\nvidia-cudnn-cu116_4994233f70074008ba039aafdf42b466\setup.py", line 152, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-cudnn-cu116
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
```

**Comment by JCBrouwer** [comment]
Ahh yeah, my bad, that's an nvidia package so it should be installed with: `pip install nvidia-cudnn-cu116 --extra-index-url https://pypi.ngc.nvidia.com`

Could you try again?

I guess that the original error is related to installing on windows. I don't have a windows machine so I haven't been able to test that yet. Thanks for being the first guinea pig!

Not sure why windows is complaining about the length of the filename. It's only 146 chars but apparently windows' limit is 255.
